### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by MrCharli3** [TomGrill/gdx-firebase#1]
Hi Tom,

What is the status of this library? Would you call it ready for production use?
I am going to use firebase and will start implementing it soon, would be nice to use this library but I'm just unclear on if it is ready for Android/iOS use?

If not, when will it be? If that is possible to answer ^^

**Comment by TomGrill** [comment]
Not for production I think. Only Database and Auth have some implementations. Other FB features are missing. iOS needs robovm bindings.
Don't think it will ever be. I will probably only add things I need for my own projects.

**Comment by MrCharli3** [comment]
Created an empty LibGdx app a few hours ago, now have working auth with email/fb/google, database-communication, push notifications working. Where did Firebase hide all my life?
You can close this :)

PS: Im using Gdx-Facebook together with Firebase, works like a charm!

**Comment by MrCharli3** [comment]
@TomGrill Sorry to bother you, but since there is no docs on using libgdx with firebase I'm not sure where else to turn. 

I ran into a problem I cannot solve. Reading from a database using firebase is easy enough, 

```
public User getUser() {
        mDatabase.child("user").child(getCurrentUser().getUid()).addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                user = dataSnapshot.getValue(User.class);
                Log.d("DATABASE", "Value is: " + user.getUsername());
            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.w("DATABASE", "Failed to read value.", error.toException());
            }
        });

        return user; //returns null
    }
```

If I use an interface in LibGdx and call this, it does not wait for the onDataChanged() to return the value, so the value returns null. I made a Callback Interface, and that works, but then my values are stuck inside that class, not sure how to reach them. Is there a simple way to send data from firebase db to libgdx?

**Comment by TomGrill** [comment]
That is just how FB works. All requests get their results within a callback/listener (ValueEventListener). A method like above will not work since FB does the real database request in another thread. That's why this calls returns null.

You need to structure your code for that kind of callback-pattern.
