### ISSUE TITLE
Under active development?

### ISSUE THREAD

**Issue by jrdzha** [TomGrill/gdx-firebase#2]
Hi,

Is this gdx extension still under active development?

Thanks,
Jahrudz

**Comment by TomGrill** [comment]
Yes it is. However I do currently only add what I need for my projects. There are no plans to cover all FB features.

**Comment by jrdzha** [comment]
Ah I see... is there anywhere where I can find a list of functionalities that have been implemented? Currently the README says the realtime database is 5% completed?

**Comment by jrdzha** [comment]
According to gdx-firebase/core/src/de/tomgrill/gdxfirebase/core/FirebaseFeatures.java Realtime Database and Authentication are implemented? Are the fully functional? Thanks!

**Comment by TomGrill** [comment]
Database and Auth are working for Desktop and Android. WebGL and iOS are not yet implemented.

**Comment by jrdzha** [comment]
Thanks for the quick reply. Any plans to include the two platforms (iOS specifically) in the future?

**Comment by TomGrill** [comment]
When somebody does it and makes a PR oder when I need it for my own projects.
